"""initial schema

Revision ID: 9b949aa9c11d
Revises: 
Create Date: 2026-05-03 14:23:30.897957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b949aa9c11d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_hash', 'model', name='uq_ai_cache_prompt_model')
    )
    op.create_index('ix_ai_cache_expires', 'ai_cache', ['expires_at'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('default_domain', sa.String(length=512), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=False)
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('proxy_url', sa.String(length=1024), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_secret', sa.LargeBinary(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('health_state', sa.String(length=32), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('citation_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_url', sa.Text(), nullable=False),
    sa.Column('region_tags', sa.JSON(), nullable=True),
    sa.Column('requires_playwright', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('pack_version', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citation_sources_project_id'), 'citation_sources', ['project_id'], unique=False)
    op.create_table('competitor_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_targets_project_id'), 'competitor_targets', ['project_id'], unique=False)
    op.create_table('integration_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_label', sa.String(length=255), nullable=False),
    sa.Column('encrypted_tokens_blob', sa.LargeBinary(), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_accounts_project_id'), 'integration_accounts', ['project_id'], unique=False)
    op.create_index('ix_integration_project_provider', 'integration_accounts', ['project_id', 'provider'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress_pct', sa.Float(), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('result_summary_json', sa.JSON(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_project_id'), 'jobs', ['project_id'], unique=False)
    op.create_index('ix_jobs_project_status_created', 'jobs', ['project_id', 'status', 'created_at'], unique=False)
    op.create_index('ix_jobs_type_status', 'jobs', ['type', 'status'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.String(length=512), nullable=False),
    sa.Column('locale', sa.String(length=64), nullable=True),
    sa.Column('device', sa.String(length=32), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_keywords_project_archived', 'keywords', ['project_id', 'archived_at'], unique=False)
    op.create_index(op.f('ix_keywords_project_id'), 'keywords', ['project_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=512), nullable=False),
    sa.Column('address_line1', sa.String(length=512), nullable=True),
    sa.Column('address_line2', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('postal_code', sa.String(length=32), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('primary_phone_e164', sa.String(length=32), nullable=True),
    sa.Column('primary_url', sa.String(length=1024), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_project_id'), 'locations', ['project_id'], unique=False)
    op.create_table('citation_checks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('requested_url', sa.Text(), nullable=True),
    sa.Column('final_url', sa.Text(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scores_json', sa.JSON(), nullable=True),
    sa.Column('response_html_gzip', sa.LargeBinary(), nullable=True),
    sa.Column('playwright_used', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['citation_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_citation_checks_loc_src', 'citation_checks', ['location_id', 'source_id', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_citation_checks_location_id'), 'citation_checks', ['location_id'], unique=False)
    op.create_index(op.f('ix_citation_checks_source_id'), 'citation_checks', ['source_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('url_norm', sa.String(length=2048), nullable=False),
    sa.Column('url_final', sa.String(length=2048), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('crawl_job_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'url_norm', name='uq_pages_project_url')
    )
    op.create_index(op.f('ix_pages_project_id'), 'pages', ['project_id'], unique=False)
    op.create_index('ix_pages_project_last_crawled', 'pages', ['project_id', 'last_crawled_at'], unique=False)
    op.create_table('serp_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('search_engine', sa.String(length=64), nullable=False),
    sa.Column('geo', sa.String(length=255), nullable=True),
    sa.Column('device', sa.String(length=32), nullable=True),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('html_gzip', sa.LargeBinary(), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_serp_keyword_fetched', 'serp_results', ['keyword_id', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_serp_results_keyword_id'), 'serp_results', ['keyword_id'], unique=False)
    op.create_table('crawl_queue_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('url_norm', sa.String(length=2048), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('parent_page_id', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawl_queue_items_job_id'), 'crawl_queue_items', ['job_id'], unique=False)
    op.create_index('ix_crawl_queue_job_state', 'crawl_queue_items', ['job_id', 'state'], unique=False)
    op.create_index('ix_crawl_queue_url', 'crawl_queue_items', ['url_norm'], unique=False)
    op.create_table('crawled_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('html_gzip', sa.LargeBinary(), nullable=True),
    sa.Column('headers_json', sa.JSON(), nullable=True),
    sa.Column('bytes_raw', sa.Integer(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawled_data_job_id'), 'crawled_data', ['job_id'], unique=False)
    op.create_index(op.f('ix_crawled_data_page_id'), 'crawled_data', ['page_id'], unique=False)
    op.create_table('page_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_page_id', sa.Integer(), nullable=False),
    sa.Column('to_url_norm', sa.String(length=2048), nullable=False),
    sa.Column('link_text', sa.String(length=512), nullable=True),
    sa.Column('nofollow', sa.Boolean(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_page_links_from', 'page_links', ['from_page_id'], unique=False)
    op.create_index(op.f('ix_page_links_from_page_id'), 'page_links', ['from_page_id'], unique=False)
    op.create_index(op.f('ix_page_links_job_id'), 'page_links', ['job_id'], unique=False)
    op.create_index('ix_page_links_to', 'page_links', ['to_url_norm'], unique=False)
    op.create_table('rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('matched_url', sa.String(length=2048), nullable=True),
    sa.Column('search_engine', sa.String(length=64), nullable=False),
    sa.Column('geo_location_label', sa.String(length=255), nullable=True),
    sa.Column('device', sa.String(length=32), nullable=True),
    sa.Column('serp_result_id', sa.Integer(), nullable=True),
    sa.Column('provenance', sa.String(length=32), nullable=False),
    sa.Column('tracked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('degraded', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['serp_result_id'], ['serp_results.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rankings_keyword_id'), 'rankings', ['keyword_id'], unique=False)
    op.create_index('ix_rankings_keyword_tracked', 'rankings', ['keyword_id', 'tracked_at'], unique=False)
    op.create_index(op.f('ix_rankings_serp_result_id'), 'rankings', ['serp_result_id'], unique=False)
    op.create_table('seo_audits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('category_scores_json', sa.JSON(), nullable=True),
    sa.Column('issues_json', sa.JSON(), nullable=True),
    sa.Column('recommendations_json', sa.JSON(), nullable=True),
    sa.Column('audited_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_audits_page_id'), 'seo_audits', ['page_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_audits_page_id'), table_name='seo_audits')
    op.drop_table('seo_audits')
    op.drop_index(op.f('ix_rankings_serp_result_id'), table_name='rankings')
    op.drop_index('ix_rankings_keyword_tracked', table_name='rankings')
    op.drop_index(op.f('ix_rankings_keyword_id'), table_name='rankings')
    op.drop_table('rankings')
    op.drop_index('ix_page_links_to', table_name='page_links')
    op.drop_index(op.f('ix_page_links_job_id'), table_name='page_links')
    op.drop_index(op.f('ix_page_links_from_page_id'), table_name='page_links')
    op.drop_index('ix_page_links_from', table_name='page_links')
    op.drop_table('page_links')
    op.drop_index(op.f('ix_crawled_data_page_id'), table_name='crawled_data')
    op.drop_index(op.f('ix_crawled_data_job_id'), table_name='crawled_data')
    op.drop_table('crawled_data')
    op.drop_index('ix_crawl_queue_url', table_name='crawl_queue_items')
    op.drop_index('ix_crawl_queue_job_state', table_name='crawl_queue_items')
    op.drop_index(op.f('ix_crawl_queue_items_job_id'), table_name='crawl_queue_items')
    op.drop_table('crawl_queue_items')
    op.drop_index(op.f('ix_serp_results_keyword_id'), table_name='serp_results')
    op.drop_index('ix_serp_keyword_fetched', table_name='serp_results')
    op.drop_table('serp_results')
    op.drop_index('ix_pages_project_last_crawled', table_name='pages')
    op.drop_index(op.f('ix_pages_project_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_citation_checks_source_id'), table_name='citation_checks')
    op.drop_index(op.f('ix_citation_checks_location_id'), table_name='citation_checks')
    op.drop_index('ix_citation_checks_loc_src', table_name='citation_checks')
    op.drop_table('citation_checks')
    op.drop_index(op.f('ix_locations_project_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_keywords_project_id'), table_name='keywords')
    op.drop_index('ix_keywords_project_archived', table_name='keywords')
    op.drop_table('keywords')
    op.drop_index('ix_jobs_type_status', table_name='jobs')
    op.drop_index('ix_jobs_project_status_created', table_name='jobs')
    op.drop_index(op.f('ix_jobs_project_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_integration_project_provider', table_name='integration_accounts')
    op.drop_index(op.f('ix_integration_accounts_project_id'), table_name='integration_accounts')
    op.drop_table('integration_accounts')
    op.drop_index(op.f('ix_competitor_targets_project_id'), table_name='competitor_targets')
    op.drop_table('competitor_targets')
    op.drop_index(op.f('ix_citation_sources_project_id'), table_name='citation_sources')
    op.drop_table('citation_sources')
    op.drop_table('settings')
    op.drop_table('proxies')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_ai_cache_expires', table_name='ai_cache')
    op.drop_table('ai_cache')
    # ### end Alembic commands ###
